INSERT INTO T_USER VALUES(1, 'teacher','1','002');
INSERT INTO T_USER VALUES(2, 'student','1','001');
INSERT INTO T_USER VALUES(3, 'Admin','admin','admin');

INSERT INTO T_STUDENT VALUES(1, '18','张三','男','001');
INSERT INTO T_STUDENT VALUES(2, '19','李四','男','002');
INSERT INTO T_STUDENT VALUES(3, '20','王五','男','003');

INSERT INTO T_TEACHER  VALUES(1, '王老师','001');
INSERT INTO T_TEACHER  VALUES(2, '李老师','001');

INSERT INTO T_COURSE  VALUES(1, '001','语文','1');
INSERT INTO T_COURSE  VALUES(2, '002','数学','1');
INSERT INTO T_COURSE  VALUES(3, '003','英语','1');


 